injury_extents = {5: {'light': 1.,
                      'moderate': 0.,
                      'grave': 0.},
                  6: {'light': 0.8775,
                      'moderate': 0.0817,
                      'grave': 0.0408},
                  7: {'light': 0.8229,
                      'moderate': 0.1094,
                      'grave': 0.0677},
                  8: {'light': 0.7751,
                      'moderate': 0.1336,
                      'grave': 0.0913},
                  9: {'light': 0.3703,
                      'moderate': 0.3085,
                      'grave': 0.3212},
                  10: {'light': 0.3012,
                       'moderate': 0.3316,
                       'grave': 0.3672},
                  11: {'light': 0.284,
                       'moderate': 0.3168,
                       'grave': 0.3992},
                  12: {'light': 0.2699,
                       'moderate': 0.2997,
                       'grave': 0.4304}
                  }

special_teams_distr = {3: {'thoracoabdominal': 1,
                           'trauma': 1,
                           'neuro': 1},
                       4: {'thoracoabdominal': 2,
                           'trauma': 1,
                           'neuro': 1},
                       5: {'thoracoabdominal': 3,
                           'trauma': 1,
                           'neuro': 1},
                       6: {'thoracoabdominal': 4,
                           'trauma': 1,
                           'neuro': 1},
                       7: {'thoracoabdominal': 4,
                           'trauma': 1,
                           'neuro': 2},
                       8: {'thoracoabdominal': 5,
                           'trauma': 1,
                           'neuro': 2},
                       9: {'thoracoabdominal': 6,
                           'trauma': 1,
                           'neuro': 2},
                       10: {'thoracoabdominal': 7,
                           'trauma': 1,
                           'neuro': 2}}
